
platform :ios, '9.3'
use_frameworks! :linkage => :static

def shared_pods
  pod 'SwiftyJSON', '4.2.0'
  pod 'SwiftLint', '0.31.0'
  pod 'PerseusUISystemKit', '1.1.2'
end

target 'Weather' do
  # Pods for Weather
  shared_pods
  
  target 'WeatherTests' do
    inherit! :search_paths
    # Pods for testing only
    
  end
end
