# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks! :linkage => :static

def shared_pods
  pod 'SwiftyJSON'
end

target 'Weather' do
  # Pods for Weather
  shared_pods
  
  target 'WeatherTests' do
    inherit! :search_paths
    # Pods for testing
    
  end
end
